name: build

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. 1.2.3)"
        required: true
        type: string

env:
  GO_VERSION: "1.24"
  FLUTTER_CHANNEL: "master"
  FLUTTER_VERSION: "80f4a0f251b" # tag, commit or branch

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: Create or update release
        id: release
        if: github.event_name == 'push'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows-matrix:
    needs: [release]
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            os: windows-11-arm
            llvm_ver: "20251202" # Only ARM64
          - arch: x64
            os: windows-2022
            llvm_ver: ""

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Install LLVM environment only on ARM64
      - name: Install llvm-mingw-ucrt-aarch64 (ARM64 only)
        if: matrix.arch == 'arm64'
        run: |
          $ver = "${{ matrix.llvm_ver }}"
          $url = "https://github.com/mstorsjo/llvm-mingw/releases/download/$ver/llvm-mingw-$ver-ucrt-aarch64.zip"
          $zip = "$env:RUNNER_TEMP\\llvm.zip"
          $extract = "$env:RUNNER_TEMP\\extract"
          $target = "C:\\clangarm64"

          curl -L $url -o $zip
          rm -r -fo $extract,$target -ea Ignore
          mkdir $extract | Out-Null

          tar -xf $zip -C $extract
          mv (Get-ChildItem $extract)[0].FullName $target

          $b = "$target\\bin"
          "CC=$b\\clang.exe"        >> $env:GITHUB_ENV
          "CXX=$b\\clang++.exe"     >> $env:GITHUB_ENV
          "CLANGARM64_BIN=$b"       >> $env:GITHUB_ENV
          "CGO_ENABLED=1"           >> $env:GITHUB_ENV
          "CLANGARM64_ROOT=$target" >> $env:GITHUB_ENV
          $b >> $env:GITHUB_PATH

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL}}
          flutter-version: ${{ env.FLUTTER_VERSION}}

      - name: Resolve version
        id: get_version
        shell: pwsh
        run: |
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            $version = "${{ inputs.version }}"
          } else {
            $raw = "${{ needs.release.outputs.tag_name }}"
            $version = $raw -replace '^v', ''
          }
          if (-not $version) { Write-Error "VERSION is empty" }
          echo "VERSION=$version" >> $env:GITHUB_ENV
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Build
        env:
          GOARCH: ${{ matrix.arch == 'x64' && 'amd64' || 'arm64' }}
        run: |
          Invoke-WebRequest -Uri "https://github.com/jrsoftware/issrc/raw/main/Files/Languages/Unofficial/ChineseSimplified.isl" -OutFile "ChineseSimplified.isl"
          mv ChineseSimplified.isl "C:\Program Files (x86)\Inno Setup 6\Languages\"

          go build -tags nosqlite -ldflags="-w -s -X github.com/GopeedLab/gopeed/pkg/base.Version=$env:VERSION" -buildmode=c-shared -o ui/flutter/windows/libgopeed.dll github.com/GopeedLab/gopeed/bind/desktop
          go build -ldflags="-w -s" -o ui/flutter/assets/exec/host.exe github.com/GopeedLab/gopeed/cmd/host
          go build -ldflags="-w -s" -o ui/flutter/assets/exec/updater.exe github.com/GopeedLab/gopeed/cmd/updater

          cd ui/flutter
          flutter build windows --release

          $release = "build\windows\${{ matrix.arch }}\runner\Release\"
          $system = "C:\Windows\System32"

          if ("${{ matrix.arch }}" -eq "arm64") {
              # for ARM64
              $mingw = "$env:CLANGARM64_ROOT\aarch64-w64-mingw32\bin"
              cp $mingw\libc++.dll $release
          } else {
              # for x64
              $mingw = "C:\Program Files\Git\mingw64\bin"
              cp $mingw\libstdc++-6.dll $release
              cp $mingw\libgcc_s_seh-1.dll $release
          }

          cp $mingw\libwinpthread-1.dll $release
          cp $system\msvcp140.dll $release
          cp $system\vcruntime140.dll $release
          cp $system\vcruntime140_1.dll $release

          cd build/windows
          echo @"
          ; Script generated by the Inno Setup Script Wizard.
          ; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
          #define MyAppName "Gopeed(Fluent)"
          #define MyAppVersion "$env:VERSION"
          #define MyAppPublisher "Minessential"
          #define MyAppURL "https://github.com/Minessential/gopeed-fluent"
          #define MyAppExeName "gopeed.exe"
          #define Architectures "${{ matrix.arch }}"
          [CustomMessages]
          english.DeleteUserData=Would you like to delete all user data and settings?%n(Located in %APPDATA%\Gopeed(Fluent) folder)
          chinesesimplified.DeleteUserData=是否同时删除所有用户数据和设置？%n(位于 %APPDATA%\Gopeed(Fluent) 文件夹)
          [Setup]
          ; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
          ; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
          AppId={{0197064E-A982-7D4A-8AAA-B3F15AF86E60}
          AppName={#MyAppName}
          AppVersion={#MyAppVersion}
          ;AppVerName={#MyAppName} {#MyAppVersion}
          AppPublisher={#MyAppPublisher}
          AppPublisherURL={#MyAppURL}
          AppSupportURL={#MyAppURL}
          AppUpdatesURL={#MyAppURL}
          DefaultDirName={autopf}\{#MyAppName}
          ; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
          ; on anything but x64 and Windows 11 on Arm.
          ArchitecturesAllowed=x64compatible
          ; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
          ; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
          ; meaning it should use the native 64-bit Program Files directory and
          ; the 64-bit view of the registry.
          ArchitecturesInstallIn64BitMode=x64compatible
          DisableProgramGroupPage=yes
          LicenseFile=..\..\..\..\LICENSE
          ; Uncomment the following line to run in non administrative install mode (install for current user only).
          ;PrivilegesRequired=lowest
          OutputDir=Output
          OutputBaseFilename=gopeed
          UninstallDisplayIcon={app}\{#MyAppExeName}
          Compression=lzma
          SolidCompression=yes
          WizardStyle=modern
          LanguageDetectionMethod=uilanguage
          ShowLanguageDialog=yes
          CloseApplications=force
          [Languages]
          Name: "english"; MessagesFile: "compiler:Default.isl"
          Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
          [Tasks]
          Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
          [Files]
          ;Source: ".\{#Architectures}\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
          ;Source: ".\{#Architectures}\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
          Source: "${{ matrix.arch }}\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs;
          ; NOTE: Don't use "Flags: ignoreversion" on any shared system files
          [UninstallDelete]
          Type: filesandordirs; Name: "{app}"
          [Code]
          procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
          var
            AppDataPath: string;
            ExitCode: Integer;
          begin
            if CurUninstallStep = usUninstall then
            begin
              if MsgBox(CustomMessage('DeleteUserData'), mbConfirmation, MB_YESNO) = IDYES then
              begin
                // Close related processes
                Exec('taskkill', '/F /IM gopeed.exe', '', SW_HIDE, ewWaitUntilTerminated, ExitCode);
                Exec('taskkill', '/F /IM host.exe', '', SW_HIDE, ewWaitUntilTerminated, ExitCode);
                // Delete the data folder
                AppDataPath := ExpandConstant('{userappdata}\Gopeed(Fluent)');
                if DirExists(AppDataPath) then
                begin
                  DelTree(AppDataPath, True, True, True);
                end;
                
                // Delete data in LocalAppData
                AppDataPath := ExpandConstant('{localappdata}\Gopeed(Fluent)');
                if DirExists(AppDataPath) then
                begin
                  DelTree(AppDataPath, True, True, True);
                end;
                
                // Delete related registry keys
                RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Google\Chrome\NativeMessagingHosts\com.gopeed.gopeed');
                RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Mozilla\NativeMessagingHosts\com.gopeed.gopeed');
                // Delete torrent protocol and file association registry keys
                RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Classes\magnet');
                RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Classes\.torrent');
                RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Classes\Gopeed_torrent');
              end;
            end;
            
            if CurUninstallStep = usDone then
            begin
              // Try to delete the installation directory after uninstallation (if there are any leftovers)
              DelTree(ExpandConstant('{app}'), True, True, True);
            end;
          end;
          [Icons]
          Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
          Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
          [Run]
          Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
          "@ > setup.iss
          iscc.exe setup.iss

          mv "Output\gopeed.exe" "Output\Gopeed_Fluent_$env:VERSION_windows_${{ matrix.arch }}.exe"

      - name: Upload
        if: github.event_name == 'push'
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ui/flutter/build/windows/Output/*
          overwrite: true

      - name: Upload build artifact (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: Gopeed_Fluent_${{ steps.get_version.outputs.version }}_windows_${{ matrix.arch }}_TEST
          path: ui/flutter/build/windows/Output/*.exe
          retention-days: 7
